### PR TITLE
Make neato sensor

### PR DESCRIPTION
**Pull request by Pingviinituutti**
The commit aaf95100406138966a8dc1d3eb53f7392bab912a should be working nicely, however, I can't get the neato state to update via websocket to dashboard without refreshing the whole page in the browser.

Commit 7717eaa2f988b759b837cd0f8afdd8858f598415 has a suggestion on how to poll for the robot state in a smarter way without constantly spamming beehive.

### CODE REVIEW

**Comment by FruitieX** [comment]
let's move this into a separate project!

do you want to take the initiative or shall I? 😃

**Comment by Pingviinituutti** [comment]
If I can steal your mqtt boilerplate code I can then move more of the neato api stuff into a new project 👌

**Comment by FruitieX** [comment]
Yess go ahead, the boilerplate is worth something now too when it's able to function after reconnects 🤪

**Comment by Pingviinituutti** [comment]
This should be working now https://github.com/Pingviinituutti/neato-mqtt

**Pull request closed without merging**
